=== kesh6190/edd-bakery/contact.xsd
<?xml version="1.0" encoding="UTF-8" ?>
	<xs:schema elementFormDefault="qualified"
			xmlns:xs="http://www.w3.org/2001/XMLSchema" >
			
	<xs:element name="feedback_db">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="feedback" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="user">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="fullname" type="xs:string" />
										<xs:element name="email" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="subject" type="xs:string" />
							<xs:element name="message" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
				
	</xs:schema>

=== kesh6190/edd-bakery/contact.xml
<?xml version="1.0" encoding="UTF-8"?>
<feedback_db xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contact.xsd">
	<feedback>
		<user>
			<fullname/>
			<email/>
		</user>	
		<subject/>
		<message/>
	</feedback>
<feedback><user><fullname/><email/></user><subject/><message/></feedback><feedback><user><fullname>Neshen Mooneesamy</fullname><email>nesh@hotmail.com</email></user><subject>bad service</subject><message>foul words</message></feedback></feedback_db>
